blank_issues_enabled: true
  contact_links:
    - name: Community Discord
      url: https://discord.io/celestial
      about: If you need assistance, feel free to join the Discord to report any issues.